// Generated by CoffeeScript 1.10.0
(function() {
  var API, Promise, get_data, get_meta, get_topic_tree, read_odata;

  Promise = require("promise");

  read_odata = require("./utils").read_odata;

  API = "http://opendata.cbs.nl/ODataApi/odata";

  get_meta = function(table, callback) {
    var keys, store, url;
    store = {};
    url = API + "/" + table;
    keys = [];
    return read_odata(url).then(function(metadata) {
      var j, len, md, parts;
      parts = [];
      for (j = 0, len = metadata.length; j < len; j++) {
        md = metadata[j];
        if (md.name === "UntypedDataSet" || md.name === "TypedDataSet") {
          continue;
        }
        keys.push(md.name);
        parts.push(read_odata(md.url));
      }
      return Promise.all(parts);
    }).then(function(parts) {
      var i, j, metadata, ref;
      metadata = {};
      for (i = j = 0, ref = parts.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        metadata[keys[i]] = parts[i];
      }
      return metadata;
    }).nodeify(callback);
  };


  /* Get data via API, which is restricted to 10 000 rows */

  get_data = function(table, filter, select, callback) {
    var url;
    url = API + "/" + table + "/TypedDataSet";
    return read_odata(url, filter, select).nodeify(callback);
  };

  get_topic_tree = function(meta) {
    var col, dataprops, idx, j, k, l, len, len1, len2, parent, roots, set_title;
    dataprops = meta.DataProperties;
    idx = {};
    for (j = 0, len = dataprops.length; j < len; j++) {
      col = dataprops[j];
      idx[col.ID] = col;
    }
    roots = [];
    for (k = 0, len1 = dataprops.length; k < len1; k++) {
      col = dataprops[k];
      if (col.ParentID && (parent = idx[col.ParentID])) {
        if (parent.children == null) {
          parent.children = [];
        }
        parent.children.push(col);
      } else {
        roots.push(col);
      }
    }
    set_title = function(mcol, prefix) {
      var child, l, len2, ref, results;
      if (prefix == null) {
        prefix = "";
      }
      mcol.title = "" + prefix + mcol.Title;
      if (mcol.children) {
        ref = mcol.children;
        results = [];
        for (l = 0, len2 = ref.length; l < len2; l++) {
          child = ref[l];
          results.push(set_title(child, mcol.title + "|"));
        }
        return results;
      }
    };
    for (l = 0, len2 = roots.length; l < len2; l++) {
      col = roots[l];
      set_title(col);
    }
    return roots;
  };

  module.exports = {
    get_meta: get_meta,
    get_data: get_data
  };


  /* Testing
  get_meta("81251ned", console.log)
  #get_meta("70636eng").then(console.log).catch(console.log)
  get_data("81251ned", 
  	{Perioden: ['2010MM12','2011MM12'], WoonregioS:['NL10  ']}).then((results) -> console.log results[0], results.length)
  get_meta("81251ned", console.log)
  get_meta("81251ned").then console.log
  get_data("81251ned", 
  	{Perioden: ['2010MM12','2011MM12'], WoonregioS:['NL10  ']})
  .then((results) -> console.log results[0], results.length)
  
  get_meta("81037ned")
  .then(get_topic_tree)
  .then(console.log)
   */

}).call(this);
