// Generated by CoffeeScript 1.12.7
(function() {
  var BULK, Promise, get_data, get_meta, read_odata;

  Promise = require("promise");

  read_odata = require("./utils").read_odata;

  BULK = "https://opendata.cbs.nl/ODataFeed/odata";

  get_meta = function(table, callback) {
    var keys, store, url;
    store = {};
    url = BULK + "/" + table;
    keys = [];
    return read_odata(url).then(function(metadata) {
      var j, len, md, parts;
      parts = [];
      for (j = 0, len = metadata.length; j < len; j++) {
        md = metadata[j];
        if (md.name === "UntypedDataSet" || md.name === "TypedDataSet") {
          continue;
        }
        keys.push(md.name);
        parts.push(read_odata(md.url));
      }
      return Promise.all(parts);
    }).then(function(parts) {
      var i, j, metadata, ref;
      metadata = {};
      for (i = j = 0, ref = parts.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        metadata[keys[i]] = parts[i];
      }
      return metadata;
    }).nodeify(callback);
  };

  get_data = function(table, filter, select, stream) {
    var url;
    url = BULK + "/" + table + "/TypedDataSet";
    return read_odata(url, filter, select);
  };

  module.exports = {
    get_meta: get_meta,
    get_data: get_data
  };


  /* Testing
  get_meta("81251ned", console.log)
  get_data("81251ned",{Perioden: ['2010MM12','2011MM12'], WoonregioS:['NL10  ']}).
  then( (results) -> console.log results[0], results.length)
   */

}).call(this);
