// Generated by CoffeeScript 1.8.0
(function() {
  var CATALOG, cb, get_featured, get_filter, get_table_featured, get_tables, get_themes, http, utils;

  http = require("http");

  utils = require("./utils");

  CATALOG = "http://opendata.cbs.nl/ODataCatalog";

  get_filter = require("./utils").get_filter;

  cb = require("./utils").cb;

  get_tables = function(filter, callback) {
    var url;
    if (callback == null) {
      callback = cb;
    }
    url = "" + CATALOG + "/Tables?$format=json";
    url += get_filter(filter);
    return http.get(url, function(res) {
      var data;
      res.setEncoding('utf8');
      data = "";
      res.on("data", function(chunk) {
        return data += chunk;
      });
      return res.on("end", function() {
        data = (JSON.parse(data)).value;
        return callback(null, data);
      });
    });
  };

  get_themes = function(filter, callback) {
    var url;
    if (callback == null) {
      callback = cb;
    }
    url = "" + CATALOG + "/Themes?$format=json";
    url += get_filter(filter);
    console.log(url);
    return http.get(url, function(res) {
      var data;
      res.setEncoding('utf8');
      data = "";
      res.on("data", function(chunk) {
        return data += chunk;
      });
      return res.on("end", function() {
        data = (JSON.parse(data)).value;
        return callback(null, data);
      });
    });
  };

  get_featured = function(filter, callback) {
    var url;
    if (callback == null) {
      callback = cb;
    }
    url = "" + CATALOG + "/Featured?$format=json";
    url += get_filter(filter);
    console.log(url);
    return http.get(url, function(res) {
      var data;
      res.setEncoding('utf8');
      data = "";
      res.on("data", function(chunk) {
        return data += chunk;
      });
      return res.on("end", function() {
        data = (JSON.parse(data)).value;
        return callback(null, data);
      });
    });
  };

  get_table_featured = function(filter, callback) {
    var url;
    if (callback == null) {
      callback = cb;
    }
    url = "" + CATALOG + "/Table_Featured?$format=json";
    url += get_filter(filter);
    console.log(url);
    return http.get(url, function(res) {
      var data;
      res.setEncoding('utf8');
      data = "";
      res.on("data", function(chunk) {
        return data += chunk;
      });
      return res.on("end", function() {
        data = (JSON.parse(data)).value;
        return callback(null, data);
      });
    });
  };

  module.exports = {
    get_tables: get_tables,
    get_themes: get_themes,
    get_table_featured: get_table_featured,
    get_featured: get_featured
  };

}).call(this);
