// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = {
    api: require("./api"),
    bulk: require("./bulk"),
    catalog: require("./catalog")
  };


  /*api = require "./api"
  catalog = require "./catalog"
  api.get_meta "81251ned"
   */

}).call(this);
