// Generated by CoffeeScript 1.9.0
(function() {
  var Promise, get_column_filter, get_filter, get_select, parse_url, read_odata, request;

  request = require("request");

  parse_url = (require("url")).parse;

  Promise = require("promise");

  read_odata = function(url, filter, select) {
    var promise;
    url += "?$format=json";
    url += get_filter(filter);
    url += get_select(select);
    promise = new Promise(function(resolve, reject) {
      var options;
      options = {
        url: url,
        withCredentials: false,
        addXDR: true
      };
      return request(url, function(error, req, body) {
        var data;
        if (!error && req.statusCode === 200) {
          data = (JSON.parse(body)).value;
          return resolve(data);
        } else {
          return reject(error || body);
        }
      });
    });
    return promise;
  };


  /*
  Create filter
   */

  get_column_filter = function(column, filter) {
    var q, value;
    if (!filter || filter.length === 0) {
      return "";
    }
    if (typeof filter === 'string') {
      filter = [filter];
    }
    q = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = filter.length; _i < _len; _i++) {
        value = filter[_i];
        _results.push(column + " eq '" + value + "'");
      }
      return _results;
    })();
    q = q.join(' or ');
    if (filter.length > 1) {
      q = "(" + q + ")";
    }
    return q;
  };

  get_filter = function(filter) {
    var column, parts, q, values;
    if (!filter || Object.keys(filter).length === 0) {
      return "";
    }
    q = "&$filter=";
    parts = (function() {
      var _results;
      _results = [];
      for (column in filter) {
        values = filter[column];
        _results.push(get_column_filter(column, values));
      }
      return _results;
    })();
    q += parts.join(" and ");
    return q;
  };

  get_select = function(select) {
    if (!select || select.length === 0) {
      return "";
    }
    if (typeof select === 'string') {
      select = [select];
    }
    return "&$select=" + select.join(",");
  };

  module.exports = {
    read_odata: read_odata
  };


  /* Testing
  
  get_meta("81251ned")
  get_data("81251ned", [] 
  	{Perioden: ['2010MM12','2011MM12'], WoonregioS:['NL10  ']},
  	 (_, results)-> console.log results[0], results.length)
  
  get_tables({Language:'en'})
  get_themes({Language: 'en'})
  get_table_featured()
   */

}).call(this);
